version: '3'
 
services:
    nginx:
      image: nginx:1.15
      container_name: ${COMPOSE_PROJECT_NAME}_nginx_con
      working_dir: /usr/share/nginx/api
      networks:
        - public_net
      ports:
          - "${NGINX_EXPOSED_PORT}:80"
      volumes:
          - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
          - ../api:/usr/share/nginx/api
          - ../logs/nginx:/var/log/nginx
      networks:
          public_net:
              ipv4_address: ${NGINX_IP}
      depends_on:
          - php_img
    mysql_img:
        container_name: ${COMPOSE_PROJECT_NAME}_mysql_con
        build:
            context: ./mysql
            args:
                - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
                - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
        volumes:
            - ../logs/mysql:${MYSQL_LOG_DIR}
            - ../database:${MYSQL_DATA_DIR}
        networks:
            public_net:
                ipv4_address: ${MYSQL_IP}
        environment:
            - MYSQL_CONTAINER_USER=${MYSQL_CONTAINER_USER}
            - MYSQL_CONTAINER_GROUP=${MYSQL_CONTAINER_GROUP}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    php_img:
        container_name: ${COMPOSE_PROJECT_NAME}_php_con
        build:
            context: ./php
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        working_dir: ${PHP_APP_DIR}
        volumes:
            - ../api:${PHP_APP_DIR}
            - ../logs/php:${PHP_ROOT_DIR}/logs
        depends_on:
            - mysql_img
        networks:
            public_net:
                ipv4_address: ${PHP_IP}
        links:
            - mysql_img:database
        environment:
            - PHP_ROOT_DIR=${PHP_ROOT_DIR}
            - NGINX_IP=${NGINX_IP}
            - NGINX_EXPOSED=${NGINX_EXPOSED_PORT}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
            - MYSQL_IP=${MYSQL_IP}
            - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    application_img:
        container_name: ${COMPOSE_PROJECT_NAME}_angular_con
        build:
            context: ./angular
        working_dir: ${APPLICATION_DIR}
        volumes:
            - ../application:${APPLICATION_DIR}
        networks:
            public_net:
                ipv4_address: ${APPLICATION_IP}
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}